import React, { useState } from 'react';
import { ShieldCheck, ExternalLink } from 'lucide-react';

interface EulaModalProps {
  isOpen: boolean;
  onAccept: () => void;
  onDecline: () => void;
}

export default function EulaModal({ isOpen, onAccept, onDecline }: EulaModalProps) {
  const [checked, setChecked] = useState(false);

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (checked) {
      onAccept();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="w-full max-w-lg mcraft-panel p-6 shadow-2xl relative">
        {/* Header */}
        <div className="flex items-center space-x-3 border-b border-gray-800 pb-4 mb-4">
          <ShieldCheck className="h-6 w-6 text-green-500" />
          <h2 className="font-press-start text-sm text-green-500 uppercase tracking-wider">
            Minecraft EULA Acceptance
          </h2>
        </div>

        {/* Info */}
        <div className="space-y-4 text-sm text-gray-300 mb-6 font-sans">
          <p>
            To run a Minecraft server, you must agree to the Mojang End User License Agreement (EULA).
          </p>
          <div className="p-4 bg-zinc-900 border border-zinc-800 rounded text-xs space-y-2 text-gray-400">
            <p>
              By accepting below, the dashboard will automatically create a <code className="bg-black px-1.5 py-0.5 rounded text-yellow-500 font-mono">eula.txt</code> file in your server directory containing:
            </p>
            <code className="block bg-black p-2 rounded text-green-400 font-mono text-[11px] leading-tight">
              # Generated by MC Server Dashboard<br />
              eula=true
            </code>
            <p className="text-[10px]">
              This indicates your official agreement to Mojang's terms and conditions.
            </p>
          </div>
          
          <a
            href="https://aka.ms/MinecraftEULA"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center text-xs text-blue-400 hover:text-blue-300 underline"
          >
            Read the full Mojang EULA on Minecraft.net
            <ExternalLink className="h-3.5 w-3.5 ml-1" />
          </a>
        </div>

        {/* Acceptance Form */}
        <form onSubmit={handleSubmit} className="space-y-6">
          <label className="flex items-start space-x-3 p-3 bg-zinc-900/40 border border-zinc-800 rounded cursor-pointer select-none hover:bg-zinc-900/60">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-1 rounded bg-zinc-900 border-zinc-700 text-green-600 focus:ring-0 focus:ring-offset-0 h-4.5 w-4.5"
            />
            <span className="text-xs text-gray-400 leading-normal">
              I have read and actively accept the Minecraft End User License Agreement (EULA) and consent to creating the <code className="bg-black/40 px-1 py-0.5 rounded font-mono text-[10px] text-gray-300">eula.txt</code> file.
            </span>
          </label>

          <div className="flex space-x-3 justify-end pt-4 border-t border-gray-800">
            <button
              type="button"
              onClick={onDecline}
              className="mcraft-btn mcraft-btn-red px-4 py-2"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={!checked}
              className="mcraft-btn mcraft-btn-green px-4 py-2"
            >
              Accept & Start
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
